rvm:
  - 2.2.3
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database workshops_test;' -U postgres
  - createuser -s workshops
addons:
  postgresql: '9.3'
